---
abstract: "CJM's plugins for Dist::Zilla"
author:
  - 'Christopher J. Madsen <perl@cjmweb.net>'
build_requires:
  File::pushd: '0'
  Parse::CPAN::Meta: '0'
  Test::DZil: '0'
  Test::More: '0.88'
  Try::Tiny: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugins-CJM
no_index:
  directory:
    - corpus
recommends:
  Git::Wrapper: '0'
requires:
  CPAN::Meta::Converter: '2.101550'
  CPAN::Meta::Requirements: '2.121'
  Data::Dumper: '0'
  Dist::Zilla: '6'
  Dist::Zilla::Plugin::InlineFiles: '0'
  Dist::Zilla::Plugin::MakeMaker: '4.300009'
  File::Copy: '0'
  File::HomeDir: '0.81'
  File::Temp: '0.19'
  List::Util: '0'
  Module::Metadata: '0'
  Moose: '0'
  Moose::Role: '0'
  Path::Tiny: '0'
  Scalar::Util: '0'
  autodie: '0'
  namespace::autoclean: '0'
  perl: '5.008'
  version: '0.77'
resources:
  repository: git://github.com/madsen/dist-zilla-plugins-cjm.git
version: '6.000'
x_Dist_Zilla:
  perl:
    version: '5.024003'
  plugins:
    -
      class: Dist::Zilla::Plugin::FileFinder::Filter
      name: ':CheckRecommend'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename: []
          exclude_match: []
          follow_symlinks: 0
          include_dotfiles: 0
          prefix: ''
          prune_directory: []
          root: .
      name: CJM/GatherDir
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: CJM/PruneCruft
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: CJM/ManifestSkip
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: CJM/MetaJSON
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: CJM/MetaYAML
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::License
      name: CJM/License
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::Test::PrereqsFromMeta
      name: CJM/Test::PrereqsFromMeta
      version: '4.23'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: CJM/PodSyntaxTests
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: CJM/PodCoverageTests
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::PodLoom
      config:
        'Pod::Loom version': '0.08'
      name: CJM/PodLoom
      version: '5.001'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: CJM/MakeMaker
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: CJM/RunExtraTests
      version: '0.029'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: CJM/MetaConfig
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::MatchManifest
      name: CJM/MatchManifest
      version: '6.000'
    -
      class: Dist::Zilla::Plugin::RecommendedPrereqs
      name: CJM/RecommendedPrereqs
      version: '4.21'
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: CJM/CheckPrereqsIndexed
      version: '0.020'
    -
      class: Dist::Zilla::Plugin::GitVersionCheckCJM
      name: CJM/GitVersionCheckCJM
      version: '4.27'
    -
      class: Dist::Zilla::Plugin::TemplateCJM
      name: CJM/TemplateCJM
      version: '5.002'
    -
      class: Dist::Zilla::Plugin::Repository
      name: CJM/Repository
      version: '0.21'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.13.5
          repo_root: .
      name: CJM/@Git/Check
      version: '2.042'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: 'Updated Changes for %{MMMM d, yyyy}d%{ trial}t release of %v'
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.13.5
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: CJM/@Git/Commit
      version: '2.042'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          changelog: Changes
          signed: 0
          tag: '6.000'
          tag_format: '%v%t'
          tag_message: 'Tagged %N %v%{ (trial release)}t'
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.13.5
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: CJM/@Git/Tag
      version: '2.042'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - 'github master'
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.13.5
          repo_root: .
      name: CJM/@Git/Push
      version: '2.042'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: CJM/TestRelease
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: CJM/UploadToCPAN
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: CJM/ArchiveRelease
      version: '6.000'
    -
      class: tools::CompileTests
      name: =tools::CompileTests
      version: ~
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExtraTestFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':PerlExecFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '6.010'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '6.010'
x_serialization_backend: 'YAML::Tiny version 1.70'
